version: '3'
services:
  haskell-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "Haskell-App"
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
